### ISSUE TITLE
i am getting issue in login 

### ISSUE THREAD

**Issue by Finexji** [ManucrackYT/LapsusClient#114]
i setup discord thing , then the authorise button is clicked , it keep showing localhost:8000/login and showing loading , it wont get futher.
![image](https://github.com/user-attachments/assets/418860ab-7a95-4283-92fc-e145ee629276)

**Comment by ManucrackYT** [comment]
You are not using localhost, you're using an IP (192.168.212.133)

**Comment by Finexji** [comment]
> You are not using localhost, you're using an IP (192.168.212.133)

i have set the same in disrcord also 
![image](https://github.com/user-attachments/assets/b3d66132-864d-47eb-b5dd-53f8266fc248)

Still same issue

**Comment by ManucrackYT** [comment]
Send me the oauth2 part from settings.json where you have to put id, secret

**Comment by Finexji** [comment]
> Send me the oauth2 part from settings.json where you have to put id, secret

      "oauth2": {
        "_comment": "Go to https://discord.dev/ and create an application to set these up.",
        "id": "1306119443390402580",
        "secret": "QkI-angjICSNgp6SeDv**FkYA5HlB****",
        "link": "http://192.168.212.133:8000",
        "callbackpath": "/callback",
        "prompt": true,
        "ip": {
          "trust x-forwarded-for": true,
          "block": [],
          "duplicate check": true
        }
      },

**Comment by ManucrackYT** [comment]
Mmmm weird, do you get any console log/error? Are you using the original Lapsus theme with no modifications?

**Comment by Finexji** [comment]
> Mmmm weird, do you get any console log/error? Are you using the original Lapsus theme with no modifications?

yes i am using original theme no modification, i am not gettting in console log/error

**Comment by ManucrackYT** [comment]
Let's continue this conversation in Discord
