### ISSUE TITLE
This is just a helidactl clone.

### ISSUE THREAD

**Issue by lordwolfyyy** [ManucrackYT/LapsusClient#17]
this  is literaly just a helidactl clone with anything referencing helidactl replaced with lapsis
![image](https://github.com/ManucrackYT/LapsusClient/assets/155068815/1a436c69-dee5-4590-976e-accff2f00390)

**Comment by ManucrackYT** [comment]
It is not, the fact I use some parts from dashactyl as Heliactyl does doesn't mean it's a clone.
